// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikrdlyuniuphcqtdkqnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrcmRseXVuaXVwaGNxdGRrcW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2OTQ0ODAsImV4cCI6MjA4MjI3MDQ4MH0.Op6P0ENFTjAlfTvJVa21kNfgUAWsff9BqNjOzNxjLF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});